In [ ]:

# defining matrices A and B
A=([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])

B=([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

# calculating the matrix multiplication
# first row 
(AB)11=(-1)(0)+(2)(0)+(3)(2)=0+0+6=6,
(AB)12=(-1)(2)+(2)(2)+(3)(9)=-2+4+27=29,
(AB)13=(-1)(1)+(2)(-8)+(3)(-1)=-1-16-3=-20
# second row
(AB)21=(4)(0)+(-5)(0)+(6)(2)=0+0+12=12,
(AB)22=(4)(2)+(-5)(2)+(6)(-8)=8-10-48=-50,
(AB)23=(4)(1)+(-5)(-8)+(6)(-1)=4+40-6=38,
# third row
(AB)31=(7)(0)+(8)(0)+(-9)(2)=0+0-18=-18,
(AB)32=(7)(2)+(8)(2)+(-9)(-9)=14+16+72=-51,
(AB)33=(7)(1)+(8)(-8)+(-9)(-1)=7-64+9=-48

# resulting matrix will be AB
AB=([
    [6, 29, -20], 
     [12, 52, 38], 
     [-18, -51, -48]
     ])



In [7]:
import numpy as np

# defining matrices A and B
A= np.array([
    [-1, 2, 3], 
    [4, -5, 6], 
    [7, 8, -9]
    ])

B= np.array([
    [0, 2, 1], 
    [0, 2, -8], 
    [2, 9, -1]
    ])

# using np.matmul()
AB_matmul= np.matmul(A, B)
# using @ operator
AB_at= A @ B
# using np.dot()
# AB_dot= np.

# printing the output
print("Matrix A:")
print(A)
print("Matrix B:")
print(B)
print("Matrix A * B (using np.matmul()):")
print(AB_matmul)
print("Matrix A * B (using @ operator):")
print(AB_at)



Matrix A:
[[-1  2  3]
 [ 4 -5  6]
 [ 7  8 -9]]
Matrix B:
[[ 0  2  1]
 [ 0  2 -8]
 [ 2  9 -1]]
Matrix A * B (using np.matmul()):
[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]
Matrix A * B (using @ operator):
[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


In [8]:
import numpy as np

# defining matrices A and B
A= np.array([
    [-1, 2, 3], 
    [4, -5, 6], 
    [7, 8, -9]
    ])

B= np.array([
    [0, 2, 1], 
    [0, 2, -8], 
    [2, 9, -1]
    ])
# Initialize an empty result matrix with zeros
result = np.zeros ((A.shape[0], B.shape[1]))

# manual multiplication manually
for i in range(A.shape[0]): 
    for j in range(B.shape[1]):
        for k in range(A.shape[1]):
            result[i][j] += A[i][k] * B[k][j]

# print the result
print("Matrix A:")
print(A)
print("\nMatrix B:")
print(B)
print("\nMatrix Product AB (manual calculation):")
print(result)

Matrix A:
[[-1  2  3]
 [ 4 -5  6]
 [ 7  8 -9]]

Matrix B:
[[ 0  2  1]
 [ 0  2 -8]
 [ 2  9 -1]]

Matrix Product AB (manual calculation):
[[  6.  29. -20.]
 [ 12.  52.  38.]
 [-18. -51. -48.]]


In [9]:
import numpy as np

def matrix_multiplication(A, B):
    A=np.array(A)
    B=np.array(B)
    # validating matrix dimensions
    if A.shape[1] != B.shape[0]:
        raise ValueError("Matrix dimensions are not compatible for multiplication.")
    # initializing an empty result matrix with zeros 
    result = np.zeros((A.shape[0], B.shape[1]))
    # performing matrix multiplication
    for i in range(A.shape[0]):
        for j in range(B.shape[1]):
            for k in range(A.shape[1]):
                result[i][j] += A[i][k] * B[k][j]
    return result

A = [[-1, 2, 3], [4, -5, 6], [7, 8, -9]]
B = [[0, 2, 1], [0, 2, -8], [2, 9, -1]]

calculated_result = matrix_multiplication(A, B)
print("Matrix A:")
print(np.array(A))
print("Matrix B:")
print(np.array(B))
print("Result of matrix multiplication:")
print(calculated_result)


Matrix A:
[[-1  2  3]
 [ 4 -5  6]
 [ 7  8 -9]]
Matrix B:
[[ 0  2  1]
 [ 0  2 -8]
 [ 2  9 -1]]
Result of matrix multiplication:
[[  6.  29. -20.]
 [ 12.  52.  38.]
 [-18. -51. -48.]]


In [10]:
import numpy as np

def matrix_multiplication_safe(A, B):

    A=np.array(A)
    B=np.array(B)

    # validating input dimesnsions
    if A.ndim != 2 or B.ndim != 2:
        raise ValueError("Both matrices must be 2D")

    if A.shape[1] != B.shape[0]:
        raise ValueError("Number of columns in A must match number of rows in B")
    # initializing empty result matrix with zeros
    result = np.zeros((A.shape[0], B.shape[1]))

    # performing matrix multiplication
    for i in range(A.shape[0]): # iterating over rows of A
        for j in range(B.shape[1]): # iterating over columns of B
            for k in range(A.shape[1]): # iterating over columns of A and rows of B
                result[i][j] += A[i][k] * B[k][j]
    # returning result matrix
    return result 

d_ndarray = np.array([[-1, 2, 3], [4, -5, 6]])
f_ndarray = np.array([[-9, 8, 7], [6, -5, 4]])

try:
    # attempting to multiply matrices D and F
    result = matrix_multiplication_safe(d_ndarray, f_ndarray)
    print("Matrix product DF")
    print(result)
except ValueError as e:
    print("Erroe:", e)


Erroe: Number of columns in A must match number of rows in B


In [13]:
import numpy as np

def matrix_multiplication_safe_with_transpose(A, B, transpose_A=False, transpose_B=False):
    
    A=np.array(A)
    B=np.array(B)
    # Applying transposition  for the inputs
    if transpose_A:
        A = A.T
    if transpose_B:
        B = B.T
    # Checking if the matrices can be multiplied
    if A.shape[1] != B.shape[0]:
        raise ValueError("The number of columns in A must be equal to the number of rows in B.")
    # initializing an empty result matrix with zeros 
    result = np.zeros((A.shape[0], B.shape[1]))
    # Performing matrix multiplication
    for i in range(A.shape[0]):
        for j in range(B.shape[1]):
            for k in range(A.shape[1]):
                result[i][j] += A[i][k] * B[k][j]
    return result

d_ndarray=np.array([[-1,2,3],[4,-5,6]])
f_ndarray=np.array([[-9,8,7],[6,-5,4]])
# transposing matrix to make the multiplication possible
try:
    result = matrix_multiplication_safe_with_transpose(d_ndarray, f_ndarray, transpose_B=True)
    print("Matrix product D x F.T(F transposed):")
    print(result)
except ValueError as e:
    print("Errror:", e)


Matrix product D x F.T(F transposed):
[[ 46.  -4.]
 [-34.  73.]]
